# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum_mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Forums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='Publish Date')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('rating_rel', models.BigIntegerField(default=0)),
                ('rating_pop', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=3000)),
                ('pub_date', models.DateTimeField(verbose_name='Publish Date')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('rating_rel', models.BigIntegerField(default=0)),
                ('rating_pop', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='subforum_mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subforums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField(verbose_name='Publish Date')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('rating_rel', models.BigIntegerField(default=0)),
                ('rating_pop', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('op', models.TextField(max_length=3000)),
                ('pub_date', models.DateTimeField(verbose_name='Publish Date')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('rating_rel', models.BigIntegerField(default=0)),
                ('rating_pop', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=1)),
                ('birth_date', models.DateField(verbose_name='Your Birth Date')),
                ('ph_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bio', models.TextField(max_length=3000)),
                ('subs_user', models.ManyToManyField(related_name='_user_subs_user_+', to='backdb.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_achievements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achv', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=300)),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User')),
            ],
        ),
        migrations.CreateModel(
            name='User_qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qual', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=300)),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User')),
            ],
        ),
        migrations.AddField(
            model_name='threads',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User'),
        ),
        migrations.AddField(
            model_name='threads',
            name='subforum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Subforums'),
        ),
        migrations.AddField(
            model_name='subforums',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User'),
        ),
        migrations.AddField(
            model_name='subforums',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Forums'),
        ),
        migrations.AddField(
            model_name='subforum_mods',
            name='handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User'),
        ),
        migrations.AddField(
            model_name='subforum_mods',
            name='subforum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Subforums'),
        ),
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User'),
        ),
        migrations.AddField(
            model_name='posts',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Threads'),
        ),
        migrations.AddField(
            model_name='forums',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User'),
        ),
        migrations.AddField(
            model_name='forum_mods',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Forums'),
        ),
        migrations.AddField(
            model_name='forum_mods',
            name='handle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User'),
        ),
    ]
