# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag_to_subforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Subforums')),
            ],
        ),
        migrations.CreateModel(
            name='tag_to_thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('text', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='tag_to_thread',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.tags'),
        ),
        migrations.AddField(
            model_name='tag_to_thread',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Threads'),
        ),
        migrations.AddField(
            model_name='tag_to_subforum',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.tags'),
        ),
    ]
