# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backdb', '0002_auto_20161118_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='subs_forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User')),
                ('subs_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Forums')),
            ],
        ),
        migrations.CreateModel(
            name='subs_subforum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User')),
                ('subs_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Subforums')),
            ],
        ),
        migrations.CreateModel(
            name='subs_thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.User')),
                ('subs_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backdb.Threads')),
            ],
        ),
        migrations.CreateModel(
            name='subs_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_users_subber', to='backdb.User')),
                ('subs_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_users_subbed', to='backdb.User')),
            ],
        ),
    ]
