# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backdb', '0004_auto_20161130_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forums',
            name='rating_rel',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='posts',
            name='rating_rel',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='subforums',
            name='rating_rel',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='threads',
            name='rating_rel',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
